[project]
name = "ai-music-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnxruntime>=1.30.0",
    "pyside6>=6.11.2",
    "pytest>=9.1.1",
    "sounddevice>=0.5.6",
    "soundfile>=0.14.0",
]

[project.scripts]
ai-music-detector = "ai_music_detector:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "nuitka>=4.2.1",
    "ordered-set>=4.1.0",
    "zstandard>=0.25.0",
]
